[versions]
agp = "8.3.0"
jacksonDatabind = "2.14.1"
json = "20211205"
jsonSimple = "1.1.1"
junit = "4.13.2"
junitJupiter = "5.8.1"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
junitVintageEngine = "5.7.0"
material = "1.11.0"
mockitoCore = "3.12.4"
okhttp = "4.10.0"
rxandroid = "2.1.0"
rxjava = "2.2.5"
stompprotocolandroid = "1.6.6"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
json = { module = "org.json:json", version.ref = "json" }
json-simple = { module = "com.googlecode.json-simple:json-simple", version.ref = "jsonSimple" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junitVintageEngine" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
stomp-protocol-android = { module = "com.github.NaikSoftware:StompProtocolAndroid", version.ref = "stompprotocolandroid" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

